name: Deploy Simple API
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: api-artifacts
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: api-artifacts
        path: ./publish

    - name: Deploy to Azure Ubuntu Server
      env:
        AZURE_HOST: ${{ secrets.AZURE_HOST }}
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      run: |
        scp -r ./publish/* $AZURE_USERNAME@$AZURE_HOST:/var/www/myapp
        ssh $AZURE_USERNAME@$AZURE_HOST 'sudo systemctl restart myapp'
